// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcCcsq7da2NXXYK9C0Qx8qLbw4PfrEJdw',
    appId: '1:653387326860:web:296d786406fa89258562a9',
    messagingSenderId: '653387326860',
    projectId: 'applearning-80d7a',
    authDomain: 'applearning-80d7a.firebaseapp.com',
    storageBucket: 'applearning-80d7a.firebasestorage.app',
    measurementId: 'G-GD6XXQVMNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwEeIrZ3Jx0VYT4HgHmGGQhPgA1lvYLoA',
    appId: '1:653387326860:android:b45e360d9b0936bc8562a9',
    messagingSenderId: '653387326860',
    projectId: 'applearning-80d7a',
    storageBucket: 'applearning-80d7a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiIHUcVGLhQ_TE91iqV2DexUbibHKw7KI',
    appId: '1:653387326860:ios:6ed04a15c8ff821d8562a9',
    messagingSenderId: '653387326860',
    projectId: 'applearning-80d7a',
    storageBucket: 'applearning-80d7a.firebasestorage.app',
    iosClientId: '653387326860-km6anfoc2i34mu5oqdo5oa5s9337te7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.duolingo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiIHUcVGLhQ_TE91iqV2DexUbibHKw7KI',
    appId: '1:653387326860:ios:6ed04a15c8ff821d8562a9',
    messagingSenderId: '653387326860',
    projectId: 'applearning-80d7a',
    storageBucket: 'applearning-80d7a.firebasestorage.app',
    iosClientId: '653387326860-km6anfoc2i34mu5oqdo5oa5s9337te7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.duolingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcCcsq7da2NXXYK9C0Qx8qLbw4PfrEJdw',
    appId: '1:653387326860:web:82523617e14e06348562a9',
    messagingSenderId: '653387326860',
    projectId: 'applearning-80d7a',
    authDomain: 'applearning-80d7a.firebaseapp.com',
    storageBucket: 'applearning-80d7a.firebasestorage.app',
    measurementId: 'G-1TQT0626XZ',
  );
}
