// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Qe00CkGwe164Ohcxvjm-DwMZUvzwxOw',
    appId: '1:53164804901:web:184087912e4b2f60ad28cc',
    messagingSenderId: '53164804901',
    projectId: 'duolingo-942a0',
    authDomain: 'duolingo-942a0.firebaseapp.com',
    storageBucket: 'duolingo-942a0.firebasestorage.app',
    measurementId: 'G-9CWLY1E6Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2323qWWir47n9D7DUvnxm9lWYT_w9x1E',
    appId: '1:53164804901:android:7378e6474f0aa2ffad28cc',
    messagingSenderId: '53164804901',
    projectId: 'duolingo-942a0',
    storageBucket: 'duolingo-942a0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYlArWpnqdvHmLupBwljgd22cCnomypSQ',
    appId: '1:53164804901:ios:97d2d057742964b5ad28cc',
    messagingSenderId: '53164804901',
    projectId: 'duolingo-942a0',
    storageBucket: 'duolingo-942a0.firebasestorage.app',
    iosBundleId: 'com.example.duolingo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYlArWpnqdvHmLupBwljgd22cCnomypSQ',
    appId: '1:53164804901:ios:97d2d057742964b5ad28cc',
    messagingSenderId: '53164804901',
    projectId: 'duolingo-942a0',
    storageBucket: 'duolingo-942a0.firebasestorage.app',
    iosBundleId: 'com.example.duolingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Qe00CkGwe164Ohcxvjm-DwMZUvzwxOw',
    appId: '1:53164804901:web:d955ddc14b65b2d4ad28cc',
    messagingSenderId: '53164804901',
    projectId: 'duolingo-942a0',
    authDomain: 'duolingo-942a0.firebaseapp.com',
    storageBucket: 'duolingo-942a0.firebasestorage.app',
    measurementId: 'G-875WZX3BR6',
  );
}
